---
- name: Run detect script
  hosts: all
  tasks:
    - name: Copy script to remote servers
      copy:
        src: detect.sh
        dest: /tmp/detect.sh
        mode: 0775
    - name: Execute script
      command: /tmp/detect.sh
      register: script_output

    - debug:
        var: script_output.stdout_lines
