---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Kali)
    tags: always
     apt:
       upgrade: dist
       update_cache: yes
    when: ansible_distribution == "Kali"

- hosts:  web_servers
  become: true
  tasks:
  - name: install apache2 and php  packages for kali
    tags: apache,apache2,kali 
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: latest

    when: ansible_distribution ==  "Kali"
  - name: install apache2 and php packages for  (CentOS)
    tags: apache,centos,httpd
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "CentOS"




- hosts:  db_servers
  become: true
  tasks:
  - name: install mariadb  package for (Kali)
    tags: db,mariadb,kali
    dnf:
      name:
        -  mariadb
      state: latest

    when: ansible_distribution ==  "Kali"
  - name: isntall mariadb for  (CentOS)
    tags: centos,db,mariadb
      dnf:
        name:
          - mariadb
        state: latest
        when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
        package:
          name: samba
          state: latest
