- name: add ssh key for simone
  authorized_key: 
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP2UFrryLu1bOExM+rK/O/O7aJg/iBWjxEaCuq+WtJE7 ansible"

                                                              
